### ISSUE TITLE
Wont start :/

### ISSUE THREAD

**Issue by Sp4wnf3rk3l** [JarodMica/StyleTTS-WebUI#1]
Easy fix I guess... but I am to stupid :D

![image](https://github.com/user-attachments/assets/d50685de-e0da-466e-8ff0-2414114b165c)

means just not finished, yet?

**Comment by somenewaccountthen** [comment]
Maybe he forgot to check in a file.

**Comment by JarodMica** [comment]
Style Webui is more fleshed out now, closing issue but if it's still present, let me know
