### ISSUE TITLE
ModulenotfoundError: No module named 'monotonic_align'

### ISSUE THREAD

**Issue by Tupu-real** [JarodMica/StyleTTS-WebUI#10]
H there, im having this error. Can anyone help me to fix it please. thanks

**Comment by Tupu-real** [comment]
![Screenshot 2024-08-19 133819](https://github.com/user-attachments/assets/00eb5459-2322-49a7-bfbe-4d05f901c953)

**Comment by Tupu-real** [comment]
Solved

**Comment by jurandfantom** [comment]
@Tupu-real There is nothing more useful than write a problem, and just say "solved" so others can learn and refer to your solution. If possible, write down how did you managed to solve it please?
