### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.tortoise_dataset_tools.dataset_whisper_tools.train_to_phoneme'

### ISSUE THREAD

**Issue by Ionaut** [JarodMica/StyleTTS-WebUI#12]
train_to_phoneme file seems to not exist! Checked the repository at https://github.com/JarodMica/tortoise_dataset_tools/tree/master/dataset_whisper_tools and it does not seem to be a thing!

**Comment by JarodMica** [comment]
Check to make sure your repo is up-to-date, reinitialize the submodules in the manual instructions section and then pull the repo.

**Comment by Ionaut** [comment]
Thanks! That got me past that. Now I just have to add eSpeak to my system variables and I should be good to go! Hey I have to say thanks for all the videos too, man. They are really thorough and I have learned  a lot!

**Comment by Ionaut** [comment]
Just had to update from the repo and reinitialize the submodules!
