### ISSUE TITLE
Training error: soundsfile.libsndError

### ISSUE THREAD

**Issue by Tupu-real** [JarodMica/StyleTTS-WebUI#15]
![Screenshot 2024-08-20 175047](https://github.com/user-attachments/assets/cf412ea5-b00b-4c8a-8c6f-8ce8fb86fae3)
Hi there everyone....¿ any solution for this? thanks

**Comment by JarodMica** [comment]
What do the contents of your train and validation phoneme text files look like?

**Comment by Tupu-real** [comment]
Hi there.
I got a first error with the two text files phoneme text and I changed them manually, then it let me move forward but now it gives this error. So the problem is in the two text files (phoneme) that are not created with the correct name apparently. I speak from total ignorance, I hope it is understood. Thanks for answering

**Comment by Tupu-real** [comment]
The audio I've used is mp3, I've used them before with your previous version of TTS and they work fine, I've also used them as audio reference in this new version and they work, so I think the audio format is not the problem.

**Comment by JarodMica** [comment]
> Hi there. I got a first error with the two text files phoneme text and I changed them manually, then it let me move forward but now it gives this error. So the problem is in the two text files (phoneme) that are not created with the correct name apparently. I speak from total ignorance, I hope it is understood. Thanks for answering

I think this may be the issue. When you use the run phonemization button, you should get a completely new text file out from that.

If you run into issues with the dataset creation step which includes the text files, I'd like the see those error as well.

If you could copy everything that's in the terminal,  that may help out and upload it as a text file

**Comment by JarodMica** [comment]
Please reopen if this is still an issue

**Comment by Tupu-real** [comment]
Hello Harod, im so sorry i did not anwer you earlier, i had a very bussy days, no time for this, but now im back....here is the log i think there is some new errors.... here the pic,  thanks in advance.
![Screenshot 2024-08-28 104237](https://github.com/user-attachments/assets/75003b58-aa6a-4f41-9159-f356863d123a)
