### ISSUE TITLE
ModuleNotFoundError: No module named 'monotonic_align'

### ISSUE THREAD

**Issue by jurandfantom** [JarodMica/StyleTTS-WebUI#16]
Sad to say but me and Justin (youtube comment section) meet same error.

"ModuleNotFoundError: No module named 'monotonic_align'" that appear in the end when we want run script. I managed to copy that module from BARK, but every single copy I have here, have __init__.py file empty and I have another error:

` File "E:\Magazyn\Grafika\AI\Voice\Text2Voice\StyleTTS-WebUI\webui.py", line 33, in <module>
    from styletts2.utils import *
  File "E:\Magazyn\Grafika\AI\Voice\Text2Voice\StyleTTS-WebUI\venv\Lib\site-packages\styletts2\utils.py", line 1, in <module>
    from monotonic_align import maximum_path
ImportError: cannot import name 'maximum_path' from 'monotonic_align' (E:\Magazyn\Grafika\AI\Voice\Text2Voice\StyleTTS-WebUI\venv\Lib\site-packages\monotonic_align\__init__.py)`

Pinokio script dosnt work as well because of missing speaktts module (and no clue where and how to install it as pinokio structure don't have clear module folder or general installation structure).

Wonder what happened in my case. Let focus on both situation (one with missing monotonic_align" moduel where installation by pip install dosn't work, and when we copy that module from other repo and __init__.py is empty and would require some code in it.

Cheers and congrats on that release

**Comment by JarodMica** [comment]
Heya Jurand, 

What happens if you try to manually install monotonic alignin pip:

```
Pip install git+https://github.com/resemble-ai/monotonic_align.git
```

I think this is the root cause that we have to figure out

**Comment by jurandfantom** [comment]
Naturally, that approach directed me to wheels as a true cause of issue. After execute that line i get following:

`System\pip-req-build-s_s6h_5e'
  Resolved https://github.com/resemble-ai/monotonic_align.git to commit 78b985be210a03d08bc3acc01c4df0442105366f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in e:\magazyn\grafika\ai\voice\text2voice\styletts-webui\venv\lib\site-packages (from monotonic_align==1.2) (1.26.3)
Building wheels for collected packages: monotonic_align
  Building wheel for monotonic_align (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for monotonic_align (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      core.c
      F:\Temp\Temp\anaconda3\include\pyconfig.h(207): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for monotonic_align
Failed to build monotonic_align
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (monotonic_align)

(venv) E:\Magazyn\Grafika\AI\Voice\Text2Voice\StyleTTS-WebUI>`

**Comment by jurandfantom** [comment]
Update:
I spedn 2h with GPT and problem on my side was istalation of visual studio - I had it installed on C and hardlink'ed to disk F (to save space on my system drive). After nuke VC and reinstalation, wheels were computed correctly by:

. Use the x64 Developer Command Prompt

    The error indicates that cl.exe from the HostX86 folder was used, which suggests that the 32-bit compiler was invoked. However, the libraries you're trying to build might require the 64-bit version.
    Instead of using the default Developer Command Prompt, open the x64 Native Tools Command Prompt for VS 2022. Then, navigate to your project directory and try the installation again.

Command Sequence:

cmd

cd /d E:\Magazyn\Grafika\AI\Voice\Text2Voice\StyleTTS-WebUI
.\venv\Scripts\activate
pip install git+https://github.com/resemble-ai/monotonic_align.git

---------
Currently i walk through installing missing modules
-pysrt
-whisperx
-----
And now I have

(venv) (base) E:\Magazyn\Grafika\AI\Voice\Text2Voice\StyleTTS-WebUI>python webui.py
E:\Magazyn\Grafika\AI\Voice\Text2Voice\StyleTTS-WebUI\venv\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


Not sure should I be alarmed by that error in terms of soundfile
