### ISSUE TITLE
Error at the end of the first epoch:

### ISSUE THREAD

**Issue by Ionaut** [JarodMica/StyleTTS-WebUI#18]
enforce fail at inline_container.cc_595] . unexpected pos 1457862912 vs 1457862800

Dedicated GPU only reached 10.7 / 12 GB.
RTX 3060 12GB

Approx. 25 min. audio

Save freq 1
Log int 10
12 epochs
Batch size 1
Max Length 150
Diff epoch 0
Joint epoch 0

**Comment by JarodMica** [comment]
I looked around online and it's seemingly related to disk space available. Each epoch will save a 2gb model, do you have enough space?

**Comment by Ionaut** [comment]
Oh Geez, That's it. Topped off my 2TB drive! Whoops!
