### ISSUE TITLE
Tensorboard Fatal error

### ISSUE THREAD

**Issue by ozmix** [JarodMica/StyleTTS-WebUI#20]
Hi there i got this fatal error 

do i need to install something else ? or should update it ?

F:\StyleTTS-WebUI>runtime\Scripts\tensorboard.exe --logdir training
Fatal error in launcher: Unable to create process using '"C:\Users\jarod\OneDrive\Desktop\code\MY_GITHUB_UPLOADS\PACKAGES\StyleTTS2\runtime\python.exe"  "F:\StyleTTS-WebUI\runtime\Scripts\tensorboard.exe" --logdir training': The system cannot find the file specified.

**Comment by JarodMica** [comment]
No update should be necessary, I'll need to look into this for why it's not running. Tensorboard.exe should exist... But it looks like it's using my directory in there instead.

**Comment by JarodMica** [comment]
This issue should be resolved now in bf1a71bd69179f1f95d6941a58bec594696e7b55.  All you need to do is run update_package.bat and then when you launch tensorboard, it'll reconfigure it to your directory.

Reopen if you run into any issues with it, thanks!
