### ISSUE TITLE
[Info] requirement.txt needs to have a library list with their versions

### ISSUE THREAD

**Issue by emrahtoy** [JarodMica/StyleTTS-WebUI#3]
reqirements.txt does not have any version info belonging to the libraries thus every version of the libraries has been downloaded by the PIP. To prevent this and give a better ground on which version of the libraries will be installed it is mandatory to provide the versions for each of the libraries if possible.

My Pinokio script overwrites the reqirements.txt just like below;

```
SoundFile==0.12.1
munch==4.0.0
torch==2.3.1
pydub==0.25.1
pyyaml==6.0.2
librosa==0.10.2.post1
nltk==3.8.1
matplotlib==3.9.1.post1
accelerate==0.33.0
transformers==4.38.0
einops==0.8.0
einops-exts==0.0.4
tqdm==4.66.5
# typing==3.10.0.0
# typing-extensions==4.12.2
phonemizer==3.3.0
gradio==4.41.0
pysrt==1.1.2
tensorboard==2.17.0

git+https://github.com/m-bain/whisperx.git
git+https://github.com/resemble-ai/monotonic_align.git
```

typing* libraries are not necessary for Python>3.5 while the project aims for Python==3.10 thus these libraries are not required.
I hope this helps with installing problems because especially pysrt's old version has a problem for fresh installers.

**Comment by JonSingleton** [comment]
Mind sharing the ultimate versions of everything you got installed? Currently dealing with this now.
