### ISSUE TITLE
NameError: name 'split_and_recombine_text' is not defined

### ISSUE THREAD

**Issue by Denshirenji-san** [JarodMica/StyleTTS-WebUI#39]
Hello, I was excited to git pull the latest changes in hopes to have the ability to generate longer prompts. 

However, generating anything now results in "NameError: name 'split_and_recombine_text' is not defined" 
[log.txt](https://github.com/user-attachments/files/17063763/log.txt)
-error. I was able to train a voice without errors, though. Just the TTS voice generation is broken currently, for me at least.

**Comment by JarodMica** [comment]
You'll need to reinitialize the styletts2 submodule and reinstall styletts2, so check that part of the installation instructions

**Comment by Denshirenji-san** [comment]
Yes, that was it, works perfectly now! Can close the issue now, thanks for everything!
