### ISSUE TITLE
I encountered an issue while trying to install the `monotonic_align` package. The installation fails during the wheel-building process, with the following error message:

### ISSUE THREAD

**Issue by SAT431** [JarodMica/StyleTTS-WebUI#6]
Building wheels for collected packages: monotonic_align
  Building wheel for monotonic_align (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for monotonic_align (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for monotonic_align
Failed to build monotonic_align
ERROR: Could not build wheels for monotonic_align, which is required to install pyproject.toml-based projects

NOTE: i have vs c++ installed and working properly and even though Iam facing this issue

**Comment by JarodMica** [comment]
I'll look at the steps for this, I often forget build tools is required for manual installations.

Sometimes it requires a specific year of build tools as well like 2017.

**Comment by SAT431** [comment]
Thank you, sir, for your dedication. Very few people offer this kind of support for free. By the way, I am your subscriber.

**Comment by SAT431** [comment]
But, I am facing same issue. I have been trying for 6 hours but no result. So, kindly help sir🙏🙏

**Comment by SAT431** [comment]
But, I am facing same issue. I have been trying for 6 hours but no result. So, kindly help sir🙏🙏

**Comment by JarodMica** [comment]
Also, for some visuals, you might wanna take a look here: https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst/64262038#64262038

**Comment by SAT431** [comment]
I don't have coding skills, so could you please let me know when you'll release a repository package similar to AI voice cloning that's easy to install? I'm a member of your YouTube channel.

**Comment by JarodMica** [comment]
In the process of testing and validating the package right now, trying on my second computer so after this, I'll start uploading it to a drive link that I'll then share to my members.  Should be about 1-2 hours from now that everything is finished and uploaded! :)

**Comment by SAT431** [comment]
Thank you
