### ISSUE TITLE
referring to "Models" when the directory is called "models"

### ISSUE THREAD

**Issue by somenewaccountthen** [JarodMica/StyleTTS-WebUI#7]
Referring to "Models" when the directory is called "models"

def load_voice_model(voice):
    return get_file_path(root_path="**Models**", voice=voice, file_extension=".pth", error_message="No TTS model found in specified location")

Hi Jarod, i am installing in linux and came across this small inconsistency.
It will fail in case sensitive filesystems on that.

Same applies for Data directory.
I just made a link from data -> Data and from Models to models for now.

in webui.py; changed:  BASE_CONFIG_FILE_PATH = os.path.join("Configs","template_config_ft.yml")

It's training a voice on my 11Gb 2080Ti :)
83% mem in use. WOOHOO!! **Fingers crossed!**

**Comment by JarodMica** [comment]
Ah yes, this is indeed an issue on linux, I though I had fixed that so good catch!  Goodluck :)!

**Comment by somenewaccountthen** [comment]
https://github.com/user-attachments/assets/cfa877f8-c291-475c-a306-4f6a4ffda5dd

Works just fine apart from the paths.
